#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/*The program will prompt the user for a value, then generates a random value,
puts them up against each other and prints the winner
but if they enter an invalid value they will be told it is invalid and asked for a valid one.
*/
int main(void)
{
 srand(time(NULL));
 char weapon;
 char weapon2;
 int x = rand() % 3; //random number generator can only produce integer values from 0 - 2 (inclusive)
 int y = 1;
 char playAgain = 'y';
 
 /*srand is needed to generate a random value every time, it seeds the random number function rand(), 
 weapon variable contains users entered value, weapon2 variable contains random value generated by program*/
 
 printf("Welcome to Rock, Paper, Scissors\n\n");
 
 do 
 {
  /*A do, while loop is used to loop through the program for as long as the user wants to and enters 'y' after being asked if they'd like to play again, while
  loop below loops through weapon choice until user enters a valid value*/
  while (weapon != 'r' && weapon != 's' && weapon != 'p')
  {
   printf("choose your weapon,\nType \"r\" for rock, \"s\" for scissors or \"p\" for paper\n");
   scanf(" %c", &weapon);
   if (weapon != 'r' && weapon != 's' && weapon != 'p')
   {
    printf("This is not a valid option \n");
   }
  }
  if (weapon == 'r')
  {
  printf("You chose rock\n");
  }
  else if (weapon == 'p')
  {
  printf("You chose paper\n");
  }
  else
  {
  printf("You chose scissors\n");
  }
  
  if (x == 0) //x value derived from random number generator
  {
   weapon2 = 'r';
   printf("The computer chose rock\n");
  }
  else if (x == 1)
  {
   weapon2 = 'p';
   printf("The computer chose paper\n");
  }
  else if (x == 2)
  {
   weapon2 = 's';
   printf("The computer chose scissors\n");
  }

  if(weapon == 'r' && weapon2 == 'r')
  {
   printf("it's a draw\n");
  }
  else if(weapon == 'r' && weapon2 == 'p')
  {
   printf("The computer wins\n");
  }
  else if (weapon == 'r' && weapon2 == 's')
  {
   printf("You win\n");
  }
  else if(weapon == 'p' && weapon2 == 'r')
  {
   printf("You win\n");
  }
  else if(weapon == 'p' && weapon2 == 'p')
  {
   printf("It's a draw\n");
  }
  else if(weapon == 'p' && weapon2 == 's')
  {
   printf("The computer wins\n");
  }
  else if(weapon == 's' && weapon2 == 's')
  {
   printf("It's a draw\n");
  }
  else if(weapon == 's' && weapon2 == 'r') 
  {
   printf("The computer wins\n");
  }
  else if (weapon == 's' && weapon2 == 'p')
  {
   printf("You win\n");
  }
  printf("Would you like to play again?\n");
  printf("Type 'y' for yes or 'n' for no\n");
  scanf(" %c", &playAgain);
  if(playAgain == 'y')
  {
   weapon = 'l';//need to change user value to trigger prompt for user input on next round
  }
   else if(playAgain == 'n')
  {
   printf("Thank you for playing");
  }
  while (playAgain != 'y' && playAgain != 'n') //while loop ensures valid input from user to proceed
  {
   printf("that is not a valid option\n");
   printf("Type 'y' for yes or 'n' for no\n");
   scanf(" %c", &playAgain);
  }
 }
  while (playAgain != 'n'); 
  return 0;
}
